---
driver:
  name: vagrant
  require_chef_omnibus: 12.18.31
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: false
  log_level: info

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: master
    run_list:
      - recipe[elastic_opsworks::elasticsearch_setup]
    data_bags_path: test/fixtures/data_bags/master
    verifier:
      inspec_tests:
        - test/integration/shared
    attributes:
      elastic_opsworks:
        elasticsearch:
          allocated_memory: 256m
          cluster.name: test-cluster

  - name: data
    run_list:
      - recipe[elastic_opsworks::elasticsearch_setup]
    data_bags_path: test/fixtures/data_bags/data
    verifier:
      inspec_tests:
        - test/integration/shared
    attributes:
      elastic_opsworks:
        elasticsearch:
          allocated_memory: 256m
          cluster.name: test-cluster

  - name: elasticsearch
    run_list:
      - recipe[elastic_opsworks::elasticsearch_setup]
    data_bags_path: test/fixtures/data_bags/elasticsearch
    verifier:
      inspec_tests:
        - test/integration/shared
    attributes:
      elastic_opsworks:
        elasticsearch:
          allocated_memory: 256m
          cluster.name: test-cluster

  - name: kibana
    run_list:
      - recipe[elastic_opsworks::kibana_setup]
    data_bags_path: test/fixtures/data_bags/kibana
    verifier:
      inspec_tests:
        - test/integration/shared
    attributes:
      elastic_opsworks:
        elasticsearch:
          allocated_memory: 256m
          cluster.name: test-cluster

  - name: barebone
    run_list:
      - recipe[elastic_opsworks::elasticsearch_setup]
    data_bags_path: test/fixtures/data_bags/elasticsearch
    verifier:
      inspec_tests:
        - test/integration/shared
    attributes:
      elastic_opsworks:
        elasticsearch:
          allocated_memory: 256m
          cluster.name: test-cluster
        xpack:
          enabled: false
